import { AdminUser, AdminRequest, AdminStats, Expert } from "./admin-types";

export const adminStats: AdminStats = {
  totalClients: 24,
  activeRequests: 12,
  totalRevenue: 47500,
  pendingInvoices: 3,
  completedThisMonth: 8,
  revenueGrowth: 23.5,
};

export const allClients: AdminUser[] = [
  {
    id: "U001",
    name: "John Doe",
    email: "john@example.com",
    phone: "+91 98765 43210",
    role: "client",
    joinedDate: "2025-12-15",
    status: "active",
    totalRequests: 4,
    totalSpent: 3500,
  },
  {
    id: "U002",
    name: "Sarah Johnson",
    email: "sarah@techcorp.com",
    phone: "+91 98765 43211",
    role: "client",
    joinedDate: "2026-01-05",
    status: "active",
    totalRequests: 7,
    totalSpent: 12500,
  },
  {
    id: "U003",
    name: "Michael Chen",
    email: "michael@startup.io",
    phone: "+91 98765 43212",
    role: "client",
    joinedDate: "2025-11-20",
    status: "active",
    totalRequests: 3,
    totalSpent: 4200,
  },
  {
    id: "U004",
    name: "Emily Rodriguez",
    email: "emily@consulting.com",
    phone: "+91 98765 43213",
    role: "client",
    joinedDate: "2026-01-10",
    status: "inactive",
    totalRequests: 2,
    totalSpent: 1500,
  },
];

export const allAdminRequests: AdminRequest[] = [
  {
    id: "REQ-001",
    title: "Legal Contract Review",
    service: "legal",
    status: "in-progress",
    createdAt: "2026-01-20",
    description: "Need review of partnership agreement",
    priority: "high",
    budget: "$1500",
    assignedExpert: "Sarah Johnson, Legal Advisor",
    clientName: "John Doe",
    clientEmail: "john@example.com",
    assignedTo: "Sarah Johnson",
    revenue: 1500,
  },
  {
    id: "REQ-002",
    title: "Insurance Policy Renewal",
    service: "insurance",
    status: "waiting",
    createdAt: "2026-01-18",
    description: "Annual policy renewal assistance",
    priority: "medium",
    budget: "$750",
    clientName: "Sarah Johnson",
    clientEmail: "sarah@techcorp.com",
    assignedTo: "Mark Wilson",
    revenue: 750,
  },
  {
    id: "REQ-003",
    title: "AWS Cloud Infrastructure Setup",
    service: "cloud",
    status: "new",
    createdAt: "2026-01-22",
    description: "Migration to AWS with auto-scaling",
    priority: "high",
    budget: "$3000",
    clientName: "Michael Chen",
    clientEmail: "michael@startup.io",
    revenue: 3000,
  },
  {
    id: "REQ-004",
    title: "Data Analytics Dashboard",
    service: "analytics",
    status: "completed",
    createdAt: "2026-01-10",
    description: "Custom analytics dashboard for sales data",
    priority: "medium",
    budget: "$2500",
    assignedExpert: "Dr. James Lee, Data Scientist",
    clientName: "Sarah Johnson",
    clientEmail: "sarah@techcorp.com",
    assignedTo: "Dr. James Lee",
    revenue: 2500,
  },
];

export const experts: Expert[] = [
  {
    id: "EXP001",
    name: "Sarah Johnson",
    expertise: ["Legal", "Contracts", "Compliance"],
    activeRequests: 3,
    rating: 4.9,
    availability: "busy",
  },
  {
    id: "EXP002",
    name: "Mark Wilson",
    expertise: ["Insurance", "Risk Management"],
    activeRequests: 2,
    rating: 4.7,
    availability: "available",
  },
  {
    id: "EXP003",
    name: "Dr. James Lee",
    expertise: ["Data Analytics", "Machine Learning"],
    activeRequests: 4,
    rating: 4.8,
    availability: "busy",
  },
  {
    id: "EXP004",
    name: "Priya Sharma",
    expertise: ["AWS", "Azure", "Cloud Architecture"],
    activeRequests: 1,
    rating: 5.0,
    availability: "available",
  },
  {
    id: "EXP005",
    name: "David Kim",
    expertise: ["Full Stack Development", "MERN Stack"],
    activeRequests: 2,
    rating: 4.6,
    availability: "available",
  },
];
