"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { FileText, Wand2, Download, CheckCircle2, Loader2, Sparkles, AlertCircle, Copy, Check } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { incrementAiUsage, getUsage, PLAN_LIMITS } from "@/lib/usage-tracker";
import { fireLimitModal } from "@/components/global-limit-modal";

type ToolType = "contract" | "proposal";

export default function AIToolsPage() {
    const [activeTool, setActiveTool] = useState<ToolType>("contract");
    
    // Form State
    const [contractType, setContractType] = useState("nda");
    const [partyNames, setPartyNames] = useState("");
    const [projectDesc, setProjectDesc] = useState("");
    
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedDoc, setGeneratedDoc] = useState<string | null>(null);

    const docTypeLabel: Record<string, string> = {
        nda: "Non-Disclosure Agreement",
        service: "Master Service Agreement",
        freelance: "Freelance / Contractor Agreement",
    };

    const handleGenerate = () => {
        if (!partyNames && !projectDesc) return;
        
        // Quota Check from global plan limits
        const currentUsage = getUsage();
        const limits = PLAN_LIMITS[currentUsage.plan] ?? PLAN_LIMITS.starter;
        if ((currentUsage.aiUsed || 0) >= limits.aiMessages) {
            fireLimitModal("ai", limits.label, limits.aiMessages);
            return;
        }

        setIsGenerating(true);
        setGeneratedDoc(null);
        setTimeout(() => {
            // ── Real-time usage tracking ──────────────────────────────────────────
            incrementAiUsage();
            
            // ── Mark onboarding step ──────────────────────────────────────────────
            try {
                const done: string[] = JSON.parse(localStorage.getItem("mrc_onboard_done") ?? "[]");
                if (!done.includes("ai")) {
                    localStorage.setItem("mrc_onboard_done", JSON.stringify([...done, "ai"]));
                }
            } catch {}

            setIsGenerating(false);
            const today = new Date().toLocaleDateString("en-IN");
            if (activeTool === "contract") {
                setGeneratedDoc(`${docTypeLabel[contractType].toUpperCase()}

Date: ${today}

This ${docTypeLabel[contractType]} ("Agreement") is entered into by and between:
${partyNames || "[Party A]  and  [Party B]"}

1. CONFIDENTIAL INFORMATION
"Confidential Information" shall include all technical and non-technical information
provided by either party, including but not limited to trade secrets, intellectual
property, business processes, financial data, and client lists.

2. SCOPE OF WORK
${projectDesc || "[Describe the scope of engagement here.]"}

3. OBLIGATIONS
Each party agrees to: (a) protect Confidential Information with the same degree
of care it uses to protect its own; (b) not disclose to third parties without prior
written consent; (c) use solely for the purposes of this Agreement.

4. TERM
This Agreement shall remain in effect for a period of two (2) years from the date
of execution, unless terminated earlier by mutual written consent.

5. GOVERNING LAW
This Agreement shall be governed by the laws of India and any disputes resolved
in the courts of Tamil Nadu.

───────────────────────────────────────────
Generated by Morchantra AI Legal Engine · ${today}
Status: Awaiting Expert Review
DISCLAIMER: This is a draft for discussion purposes only.
───────────────────────────────────────────`);
            } else {
                setGeneratedDoc(`BUSINESS PROPOSAL

Prepared for: ${partyNames || "Prospective Client"}
Date: ${today}

EXECUTIVE SUMMARY
${projectDesc || "We propose a comprehensive engagement to address key challenges."}

Our proprietary methodology will ensure a 15–20% measurable efficiency
increase within the first quarter of engagement.

DELIVERABLES
• Strategic Analysis & Gap Report
• Implementation Roadmap (12-week plan)
• Live Dashboard & Weekly KPI Reports
• Post-engagement support (30 days)

TIMELINE & INVESTMENT
Phase 1 — Discovery (Weeks 1–2):      ₹2,00,000
Phase 2 — Implementation (Weeks 3–6): ₹9,50,000
Phase 3 — Reporting & Handoff:        ₹2,50,000

Total Investment: ₹14,00,000 (flexible milestone payments)

───────────────────────────────────────────
Generated by Morchantra AI Proposal Engine · ${today}
All figures are indicative. Final terms subject to negotiation.
───────────────────────────────────────────`);
            }
        }, 2200);
    };

    const [copied, setCopied] = useState(false);

    const copyToClipboard = () => {
        if (!generatedDoc) return;
        navigator.clipboard.writeText(generatedDoc);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadAsPDF = async () => {
        if (!generatedDoc) return;
        const { jsPDF } = await import("jspdf");
        const doc = new jsPDF({ unit: "mm", format: "a4" });
        doc.setFillColor(239, 68, 68);
        doc.rect(0, 0, 210, 18, "F");
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(11);
        doc.setFont("helvetica", "bold");
        doc.text("MORCHANTRA", 14, 11);
        doc.setFontSize(8);
        doc.setFont("helvetica", "normal");
        doc.text("AI-Generated Document — Draft Only", 100, 11);
        doc.setTextColor(30, 30, 30);
        doc.setFontSize(10);
        const lines = doc.splitTextToSize(generatedDoc, 180);
        doc.text(lines, 14, 30);
        doc.save(`${activeTool}_draft_${Date.now()}.pdf`);
    };

    return (
        <div className="space-y-8 animate-in fade-in duration-500 max-w-5xl mx-auto">
            <div>
                <h1 className="text-3xl font-bold tracking-tight text-white mb-2">Enterprise AI Agents</h1>
                <p className="text-zinc-400">Instantly generate legally-sound drafts and winning proposals using our models.</p>
            </div>

            {/* Tool Selection Tabs */}
            <div className="flex gap-4 border-b border-zinc-800 pb-px">
                <button 
                    onClick={() => { setActiveTool("contract"); setGeneratedDoc(null); }}
                    className={`pb-4 px-2 font-semibold transition-all border-b-2 flex gap-2 items-center ${activeTool === "contract" ? "border-primary text-white" : "border-transparent text-zinc-500 hover:text-zinc-300"}`}
                >
                    <FileText className="w-4 h-4" /> Smart Contract Generator
                </button>
                <button 
                    onClick={() => { setActiveTool("proposal"); setGeneratedDoc(null); }}
                    className={`pb-4 px-2 font-semibold transition-all border-b-2 flex gap-2 items-center ${activeTool === "proposal" ? "border-primary text-white" : "border-transparent text-zinc-500 hover:text-zinc-300"}`}
                >
                    <Wand2 className="w-4 h-4" /> AI Proposal Engine
                </button>
            </div>

            <div className="grid lg:grid-cols-2 gap-8">
                {/* Input Column */}
                <Card className="border-zinc-800 bg-zinc-900/50 backdrop-blur">
                    <CardContent className="p-6 space-y-6">
                        <div className="flex items-center gap-2 mb-2">
                            <Sparkles className="w-5 h-5 text-primary" />
                            <h3 className="font-bold text-lg text-white">Define Parameters</h3>
                        </div>

                        {activeTool === "contract" && (
                            <div className="space-y-4">
                                <div>
                                    <label className="text-xs font-bold uppercase tracking-wider text-zinc-500 mb-2 block">Contract Boilerplate</label>
                                    <select 
                                        value={contractType} onChange={(e) => setContractType(e.target.value)}
                                        className="w-full h-12 rounded-xl bg-zinc-950 border border-zinc-800 px-4 text-sm font-medium focus:border-primary/50 text-white outline-none"
                                    >
                                        <option value="nda">Non-Disclosure Agreement (NDA)</option>
                                        <option value="service">Master Service Agreement</option>
                                        <option value="freelance">Freelance/Contractor Agreement</option>
                                    </select>
                                </div>
                            </div>
                        )}

                        <div className="space-y-4">
                            <div>
                                <label className="text-xs font-bold uppercase tracking-wider text-zinc-500 mb-2 block">
                                    {activeTool === "contract" ? "Parties Involved" : "Client Name"}
                                </label>
                                <input 
                                    type="text" 
                                    placeholder={activeTool === "contract" ? "e.g., Morchantra LLC & Acme Corp" : "e.g., Acme Corp"}
                                    value={partyNames} onChange={(e) => setPartyNames(e.target.value)}
                                    className="w-full h-12 rounded-xl bg-zinc-950 border border-zinc-800 px-4 text-sm font-medium focus:border-primary/50 text-white outline-none placeholder:text-zinc-700"
                                />
                            </div>

                            <div>
                                <label className="text-xs font-bold uppercase tracking-wider text-zinc-500 mb-2 block">
                                    {activeTool === "contract" ? "Core Terms / Scope" : "Project Summary & Goals"}
                                </label>
                                <textarea 
                                    placeholder="Briefly describe what this covers..."
                                    value={projectDesc} onChange={(e) => setProjectDesc(e.target.value)}
                                    className="w-full h-32 rounded-xl bg-zinc-950 border border-zinc-800 p-4 text-sm font-medium focus:border-primary/50 text-white outline-none placeholder:text-zinc-700 resize-none"
                                />
                            </div>
                        </div>

                        <Button 
                            onClick={handleGenerate} 
                            disabled={isGenerating || (!partyNames && !projectDesc)}
                            className="w-full h-12 font-bold text-sm bg-primary hover:bg-primary/90 gap-2"
                        >
                            {isGenerating ? <Loader2 className="w-4 h-4 animate-spin" /> : <Wand2 className="w-4 h-4" />}
                            {isGenerating ? "Synthesizing Draft..." : `Generate ${activeTool === "contract" ? "Contract" : "Proposal"}`}
                        </Button>

                        {activeTool === "contract" && (
                            <div className="flex items-start gap-2 p-3 bg-blue-500/10 border border-blue-500/20 rounded-lg">
                                <AlertCircle className="w-4 h-4 text-blue-400 mt-0.5 shrink-0" />
                                <p className="text-[11px] text-blue-200/70 leading-relaxed">Generated contracts are drafts. Once generated, a Morchantra expert will review it automatically if requested.</p>
                            </div>
                        )}
                    </CardContent>
                </Card>

                {/* Output Column */}
                <div className="min-h-[500px] flex">
                    <AnimatePresence mode="wait">
                        {!isGenerating && !generatedDoc && (
                            <motion.div 
                                key="empty"
                                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                                className="w-full border-2 border-dashed border-zinc-800 rounded-[2rem] flex flex-col items-center justify-center text-zinc-600 p-10 text-center"
                            >
                                <FileText className="w-12 h-12 mb-4 text-zinc-700/50" />
                                <h3 className="font-semibold text-zinc-400 mb-2">Awaiting Generation</h3>
                                <p className="text-sm">Fill in the parameters and click generate. Our models will produce a structured draft instantly.</p>
                            </motion.div>
                        )}
                        
                        {isGenerating && (
                            <motion.div 
                                key="loading"
                                initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                                className="w-full border border-zinc-800 rounded-[2rem] bg-zinc-900/30 flex flex-col items-center justify-center p-10 text-center"
                            >
                                <div className="relative">
                                    <div className="w-16 h-16 rounded-full border-4 border-zinc-800" />
                                    <div className="w-16 h-16 rounded-full border-4 border-primary border-t-transparent animate-spin absolute inset-0" />
                                    <Sparkles className="w-6 h-6 text-primary absolute inset-0 m-auto animate-pulse" />
                                </div>
                                <h3 className="font-semibold text-white mt-6 mb-2">Structuring document...</h3>
                                <p className="text-sm text-zinc-500">Applying legal frameworks and best practices.</p>
                            </motion.div>
                        )}

                        {generatedDoc && !isGenerating && (
                            <motion.div 
                                key="result"
                                initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}
                                className="w-full border border-zinc-700 bg-zinc-900 shadow-2xl rounded-[2rem] overflow-hidden flex flex-col h-full"
                            >
                                <div className="h-14 border-b border-zinc-800 bg-zinc-950/50 flex items-center justify-between px-6 shrink-0">
                                    <div className="flex items-center gap-2">
                                        <CheckCircle2 className="w-4 h-4 text-emerald-400" />
                                        <span className="text-xs font-bold text-white uppercase tracking-widest leading-none mt-0.5">Draft Ready</span>
                                    </div>
                                    <div className="flex items-center gap-2">
                                        <Button size="sm" variant="outline" onClick={copyToClipboard} className="h-8 text-[11px] font-bold border-zinc-700 text-zinc-300 gap-1.5">
                                            {copied ? <Check className="w-3 h-3 text-emerald-400" /> : <Copy className="w-3 h-3" />}
                                            {copied ? "Copied!" : "Copy"}
                                        </Button>
                                        <Button size="sm" variant="outline" onClick={downloadAsPDF} className="h-8 text-[11px] font-bold border-zinc-700 text-zinc-300 gap-1.5">
                                            <Download className="w-3 h-3" /> PDF
                                        </Button>
                                    </div>
                                </div>
                                <div className="p-8 overflow-y-auto flex-1 font-serif text-zinc-300 whitespace-pre-wrap text-[15px] leading-relaxed bg-zinc-900/80">
                                    {generatedDoc}
                                </div>
                            </motion.div>
                        )}
                    </AnimatePresence>
                </div>
            </div>
        </div>
    );
}
